name: mindcheck
description: "MindCheck is an Multi-platform built with Flutter for comprehensive mental health assessment and support."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
